apiVersion: apps/v1
kind: Deployment
metadata:
  name: sings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sings
  template:
    metadata:
      labels:
        app: sings
    spec:
      containers:
      - image: okteto.dev/sings:latest
        name: sings
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "dbf8574d-3537-4f35-9ef5-f05cb0f304ad"
        - name: Vless_Path
          value: "/vl55srd4"
        - name: Vmess_UUID
          value: "dbf8574d-3537-4f35-9ef5-f05cb0f304ad"
        - name: Vmess_Path
          value: "/vm666gs3"
        - name: Share_Path
          value: "/v2link"
